apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
    spec:
      containers:
      - env:
        - name: ADMINER_DEFAULT_SERVER
          value: mysql_db
        image: adminer:latest
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
status: {}
