apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: prevail
        - name: MYSQL_HOST_IP
          value: mysql_db
        - name: MYSQL_PASSWORD
          value: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: MYSQL_USER
        name: api
        resources: {}
        volumeMounts:
        - mountPath: /app/node-modules
          name: api-claim0
        - mountPath: /app
          name: api-claim1
      restartPolicy: Always
      volumes:
      - name: api-claim0
        persistentVolumeClaim:
          claimName: api-claim0
      - name: api-claim1
        persistentVolumeClaim:
          claimName: api-claim1
status: {}
