apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - env:
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        name: client
        resources: {}
        stdin: true
        volumeMounts:
        - mountPath: /app/node-modules
          name: client-claim0
        - mountPath: /app
          name: client-claim1
      restartPolicy: Always
      volumes:
      - name: client-claim0
        persistentVolumeClaim:
          claimName: client-claim0
      - name: client-claim1
        persistentVolumeClaim:
          claimName: client-claim1
status: {}
